server:
  port: 8080
  app_mode: debug

log:
  filename: logs/access.log
  level: debug
  max_size: 10
  max_age: 30
  max_backups: 30
  compress: true
  json: true
  duration: 1440

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  db: test
  charset: utf8mb4

redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  db: 0

mongo:
  host: 1.14.58.91
  port: 27017
  user: cqcadmin
  password: dsaASdsdoOyena
  database: cqc

elastic:
  host: 127.0.0.1
  port: 9200
  sniff: false

jwt:
  accessExpire: 120  # access_token失效时长(分钟)
  refreshExpire: 10080 # refresh_token失效时长(分钟)
  secret: bingo # 签名密钥