server:
  port: 8080
  app_mode: debug

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  db: test
  charset: utf8mb4

redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  db: 0

mongo:
  host: 127.0.0.1
  port: 27017
  user: root
  password: 123456
  database: test

custom:
  user:
    age: 18