basePath: /
definitions:
  dto.Profile:
    properties:
      avatar:
        description: 头像
        type: string
      birthday:
        description: "\U0001F382"
        type: string
      created_at:
        description: 注册时间
        type: string
      email:
        description: "\U0001F4EE"
        type: string
      gender:
        description: 性别
        type: string
      id:
        type: integer
      level:
        description: 等级
        type: integer
      nickname:
        description: 昵称
        type: string
      phone:
        description: 手机号
        type: string
      signature:
        description: 个性签名
        type: string
    type: object
  dto.RegisterCount:
    properties:
      date:
        description: 年-月-日
        type: string
      total:
        description: 统计结果
        type: integer
    type: object
  dto.RegisterParam:
    properties:
      code:
        description: 短信码
        type: integer
      password:
        maxLength: 18
        minLength: 6
        type: string
      phone:
        description: 手机号
        type: string
    required:
    - code
    - password
    - phone
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: bingo案例
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Bingo Example API
  version: "1.0"
paths:
  /v1/me:
    get:
      description: 登录人信息
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.Profile'
      security:
      - ApiKeyAuth: []
      summary: 个人信息
      tags:
      - 用户
  /v1/reg-count:
    get:
      description: 按月统计当月每天注册人数
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Y-d
        in: query
        name: month
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 结果按日期分组
          schema:
            allOf:
            - type: object
            - properties:
                code:
                  type: integer
                data:
                  items:
                    $ref: '#/definitions/dto.RegisterCount'
                  type: array
                message:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 注册统计
      tags:
      - 用户
  /v1/register:
    post:
      description: 手机号码注册
      parameters:
      - description: 注册表单
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterParam'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"data":{"access_token":"","refresh_token":""},"msg":"ok"}'
          schema:
            type: object
        "400":
          description: '{"code":400,"data":null,"msg":"参数错误"}'
          schema:
            type: object
      summary: 注册
      tags:
      - 用户
  /v1/users/{id}:
    get:
      description: 手机号码注册
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息
          schema:
            $ref: '#/definitions/dto.Profile'
        "404":
          description: '{"code":404,"data":null,"msg":"未查询到结果"}'
          schema:
            type: object
      summary: 用户详情
      tags:
      - 用户
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
